
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 40;
  public static final int AC = 33;
  public static final int POR = 9;
  public static final int CHAR = 32;
  public static final int STR = 45;
  public static final int ENTERO = 41;
  public static final int INT = 29;
  public static final int IDENTBOOL = 46;
  public static final int IMPLICA = 39;
  public static final int FOR = 25;
  public static final int NOIGUAL = 12;
  public static final int CP = 4;
  public static final int NOT = 18;
  public static final int MENORIGUAL = 14;
  public static final int AND = 19;
  public static final int IGUAL = 27;
  public static final int CARACTER = 44;
  public static final int IGUALDAD = 11;
  public static final int OR = 20;
  public static final int DIV = 10;
  public static final int CC = 34;
  public static final int IF = 21;
  public static final int MAYORIGUAL = 16;
  public static final int EOF = 0;
  public static final int BOOLEAN = 17;
  public static final int TRUE = 37;
  public static final int error = 1;
  public static final int COMA = 30;
  public static final int MENOS = 8;
  public static final int MENOR = 13;
  public static final int IDENT = 42;
  public static final int MENOSUNARIO = 28;
  public static final int CLL = 6;
  public static final int REAL = 43;
  public static final int MAYOR = 15;
  public static final int ELSE = 22;
  public static final int WHILE = 23;
  public static final int FLOAT = 31;
  public static final int STRING = 36;
  public static final int LEN = 35;
  public static final int ALL = 5;
  public static final int FALSE = 38;
  public static final int AP = 3;
  public static final int PRINT = 26;
  public static final int DO = 24;
  public static final int PYC = 2;
  public static final int MAS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PYC",
  "AP",
  "CP",
  "ALL",
  "CLL",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "IGUALDAD",
  "NOIGUAL",
  "MENOR",
  "MENORIGUAL",
  "MAYOR",
  "MAYORIGUAL",
  "BOOLEAN",
  "NOT",
  "AND",
  "OR",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "PRINT",
  "IGUAL",
  "MENOSUNARIO",
  "INT",
  "COMA",
  "FLOAT",
  "CHAR",
  "AC",
  "CC",
  "LEN",
  "STRING",
  "TRUE",
  "FALSE",
  "IMPLICA",
  "FORALL",
  "ENTERO",
  "IDENT",
  "REAL",
  "CARACTER",
  "STR",
  "IDENTBOOL"
  };
}

