/* The following code was generated by JFlex 1.7.0 */


import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>PLXC.flex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int UNICODE = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\60\1\54\1\55\1\56\1\54\22\0\1\0\1\15\1\23"+
    "\3\0\1\20\1\52\1\2\1\3\1\12\1\10\1\22\1\11\1\46"+
    "\1\13\1\47\11\50\1\0\1\1\1\16\1\14\1\17\2\0\4\57"+
    "\1\51\25\57\1\6\1\53\1\7\3\0\1\36\1\43\1\42\1\33"+
    "\1\26\1\25\1\45\1\32\1\24\2\57\1\27\1\57\1\40\1\34"+
    "\1\37\1\57\1\35\1\30\1\41\1\44\1\57\1\31\3\57\1\4"+
    "\1\21\1\5\7\0\1\55\u1fa2\0\1\55\1\55\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\2\1\1\21\1\22\13\23\1\1\2\24\2\1"+
    "\1\25\1\26\3\0\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\7\23\1\36\4\23\2\0\1\24\2\0"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\0\1\45"+
    "\1\46\1\23\1\47\10\23\1\0\1\50\1\0\1\51"+
    "\2\0\3\23\1\52\3\23\1\53\1\54\1\23\1\0"+
    "\2\50\1\51\1\0\1\55\1\56\1\23\1\57\1\23"+
    "\1\60\1\61\1\23\1\0\1\62\1\63\1\64\1\23"+
    "\1\0\1\65\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[124];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\223\0\223\0\223\0\223"+
    "\0\223\0\223\0\223\0\223\0\304\0\223\0\223\0\365"+
    "\0\u0126\0\u0157\0\u0188\0\u01b9\0\u01ea\0\223\0\223\0\u021b"+
    "\0\u024c\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3"+
    "\0\u03d4\0\u0405\0\u0436\0\223\0\u0467\0\u0498\0\u04c9\0\u04fa"+
    "\0\223\0\u052b\0\u055c\0\u058d\0\223\0\223\0\223\0\223"+
    "\0\223\0\223\0\u02ae\0\u05be\0\u05ef\0\u0620\0\u0651\0\u0682"+
    "\0\u06b3\0\u06e4\0\u02ae\0\u0715\0\u0746\0\u0777\0\u07a8\0\u07d9"+
    "\0\u080a\0\u083b\0\u086c\0\u089d\0\223\0\223\0\223\0\223"+
    "\0\223\0\223\0\u08ce\0\223\0\u02ae\0\u08ff\0\u0930\0\u0961"+
    "\0\u0992\0\u09c3\0\u09f4\0\u0a25\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9"+
    "\0\u0b1a\0\u0b4b\0\u0b4b\0\u0b7c\0\u0bad\0\u0bde\0\u0c0f\0\u0c40"+
    "\0\u02ae\0\u0c71\0\u0ca2\0\u0cd3\0\u02ae\0\u02ae\0\u0d04\0\u0d35"+
    "\0\u0d66\0\u0d97\0\223\0\u0dc8\0\223\0\u02ae\0\u0df9\0\u02ae"+
    "\0\u0e2a\0\u02ae\0\u02ae\0\u0e5b\0\u0e8c\0\223\0\u02ae\0\u02ae"+
    "\0\u0ebd\0\u0eee\0\u02ae\0\223";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[124];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\33\1\36\3\33\1\37\1\33\1\40"+
    "\1\41\1\42\2\33\1\43\1\44\1\45\1\33\1\46"+
    "\4\4\1\33\1\47\23\50\1\51\27\50\1\52\1\0"+
    "\4\50\24\0\22\53\1\0\3\53\5\0\1\53\73\0"+
    "\1\54\63\0\1\55\60\0\1\56\60\0\1\57\60\0"+
    "\1\60\64\0\1\61\61\0\1\62\63\0\1\33\1\63"+
    "\12\33\1\64\5\33\1\0\3\33\5\0\1\33\25\0"+
    "\3\33\1\65\4\33\1\66\1\33\1\67\7\33\1\0"+
    "\3\33\5\0\1\33\25\0\3\33\1\70\16\33\1\0"+
    "\3\33\5\0\1\33\25\0\22\33\1\0\3\33\5\0"+
    "\1\33\25\0\15\33\1\71\4\33\1\0\3\33\5\0"+
    "\1\33\25\0\6\33\1\72\13\33\1\0\3\33\5\0"+
    "\1\33\25\0\10\33\1\73\11\33\1\0\3\33\5\0"+
    "\1\33\25\0\11\33\1\74\10\33\1\0\3\33\5\0"+
    "\1\33\25\0\11\33\1\75\10\33\1\0\3\33\5\0"+
    "\1\33\25\0\6\33\1\76\13\33\1\0\3\33\5\0"+
    "\1\33\25\0\10\33\1\77\11\33\1\0\3\33\5\0"+
    "\1\33\30\0\1\100\77\0\1\101\2\102\10\0\53\103"+
    "\1\104\3\0\2\103\56\0\1\4\2\0\23\50\1\0"+
    "\27\50\2\0\4\50\23\0\1\105\11\0\1\106\2\0"+
    "\1\107\1\110\2\0\1\111\6\0\1\112\31\0\22\113"+
    "\1\0\3\113\5\0\1\113\20\0\1\114\65\0\15\33"+
    "\1\115\4\33\1\0\3\33\5\0\1\33\25\0\10\33"+
    "\1\116\11\33\1\0\3\33\5\0\1\33\25\0\11\33"+
    "\1\117\10\33\1\0\3\33\5\0\1\33\25\0\3\33"+
    "\1\120\16\33\1\0\3\33\5\0\1\33\25\0\4\33"+
    "\1\121\15\33\1\0\3\33\5\0\1\33\25\0\11\33"+
    "\1\122\10\33\1\0\3\33\5\0\1\33\25\0\1\123"+
    "\21\33\1\0\3\33\5\0\1\33\25\0\1\124\21\33"+
    "\1\0\3\33\5\0\1\33\25\0\20\33\1\125\1\33"+
    "\1\0\3\33\5\0\1\33\25\0\12\33\1\126\7\33"+
    "\1\0\3\33\5\0\1\33\25\0\10\33\1\127\11\33"+
    "\1\0\3\33\5\0\1\33\27\0\1\130\101\0\2\131"+
    "\57\0\2\102\10\0\52\132\1\133\1\132\3\0\46\132"+
    "\1\134\5\132\1\133\1\132\3\0\2\132\24\0\22\135"+
    "\1\0\3\135\5\0\1\135\25\0\12\33\1\136\7\33"+
    "\1\0\3\33\5\0\1\33\25\0\12\33\1\137\7\33"+
    "\1\0\3\33\5\0\1\33\25\0\4\33\1\140\15\33"+
    "\1\0\3\33\5\0\1\33\25\0\2\33\1\141\17\33"+
    "\1\0\3\33\5\0\1\33\25\0\1\142\21\33\1\0"+
    "\3\33\5\0\1\33\25\0\3\33\1\143\16\33\1\0"+
    "\3\33\5\0\1\33\25\0\14\33\1\144\5\33\1\0"+
    "\3\33\5\0\1\33\25\0\2\33\1\145\17\33\1\0"+
    "\3\33\5\0\1\33\25\0\11\33\1\146\10\33\1\0"+
    "\3\33\5\0\1\33\25\0\3\33\1\147\16\33\1\0"+
    "\3\33\5\0\1\33\41\0\1\150\31\0\1\151\35\0"+
    "\2\131\1\152\61\0\1\153\33\0\2\154\4\0\1\154"+
    "\2\0\1\154\3\0\2\154\3\0\2\154\1\0\1\153"+
    "\32\0\22\155\1\0\3\155\5\0\1\155\25\0\15\33"+
    "\1\156\4\33\1\0\3\33\5\0\1\33\25\0\3\33"+
    "\1\157\16\33\1\0\3\33\5\0\1\33\25\0\2\33"+
    "\1\160\17\33\1\0\3\33\5\0\1\33\25\0\14\33"+
    "\1\161\5\33\1\0\3\33\5\0\1\33\25\0\2\33"+
    "\1\162\17\33\1\0\3\33\5\0\1\33\25\0\15\33"+
    "\1\163\4\33\1\0\3\33\5\0\1\33\25\0\2\33"+
    "\1\164\17\33\1\0\3\33\5\0\1\33\46\0\1\165"+
    "\63\0\1\151\21\0\1\151\36\0\1\151\35\0\2\154"+
    "\4\0\1\154\2\0\1\154\3\0\2\154\3\0\2\154"+
    "\1\0\1\166\32\0\3\33\1\167\16\33\1\0\3\33"+
    "\5\0\1\33\25\0\21\33\1\170\1\0\3\33\5\0"+
    "\1\33\25\0\12\33\1\171\7\33\1\0\3\33\5\0"+
    "\1\33\42\0\1\172\43\0\14\33\1\173\5\33\1\0"+
    "\3\33\5\0\1\33\33\0\1\174\26\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3871];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\11\11\1\1\2\11\6\1\2\11\14\1\1\11"+
    "\4\1\1\11\3\0\6\11\15\1\2\0\1\1\2\0"+
    "\6\11\1\0\1\11\13\1\1\0\1\1\1\0\1\1"+
    "\2\0\12\1\1\0\2\1\1\11\1\0\1\11\7\1"+
    "\1\0\1\11\3\1\1\0\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[124];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  StringBuffer string = new StringBuffer();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            } 
            // fall through
          case 55: break;
          case 2: 
            { return new Symbol(sym.PYC);
            } 
            // fall through
          case 56: break;
          case 3: 
            { return new Symbol(sym.AP);
            } 
            // fall through
          case 57: break;
          case 4: 
            { return new Symbol(sym.CP);
            } 
            // fall through
          case 58: break;
          case 5: 
            { return new Symbol(sym.ALL);
            } 
            // fall through
          case 59: break;
          case 6: 
            { return new Symbol(sym.CLL);
            } 
            // fall through
          case 60: break;
          case 7: 
            { return new Symbol(sym.AC);
            } 
            // fall through
          case 61: break;
          case 8: 
            { return new Symbol(sym.CC);
            } 
            // fall through
          case 62: break;
          case 9: 
            { return new Symbol(sym.MAS);
            } 
            // fall through
          case 63: break;
          case 10: 
            { return new Symbol(sym.MENOS);
            } 
            // fall through
          case 64: break;
          case 11: 
            { return new Symbol(sym.POR);
            } 
            // fall through
          case 65: break;
          case 12: 
            { return new Symbol(sym.DIV);
            } 
            // fall through
          case 66: break;
          case 13: 
            { return new Symbol(sym.IGUAL);
            } 
            // fall through
          case 67: break;
          case 14: 
            { return new Symbol(sym.NOT);
            } 
            // fall through
          case 68: break;
          case 15: 
            { return new Symbol(sym.MENOR);
            } 
            // fall through
          case 69: break;
          case 16: 
            { return new Symbol(sym.MAYOR);
            } 
            // fall through
          case 70: break;
          case 17: 
            { return new Symbol(sym.COMA);
            } 
            // fall through
          case 71: break;
          case 18: 
            { string.setLength(0); yybegin(STRING);
            } 
            // fall through
          case 72: break;
          case 19: 
            { String t = yytext(); if(TablaSimbolos.buscar(t)==null || !TablaSimbolos.buscar(t).esBool()) 
    			 {return new Symbol(sym.IDENT, t);} else {return new Symbol(sym.IDENTBOOL, t);}
            } 
            // fall through
          case 73: break;
          case 20: 
            { return new Symbol(sym.ENTERO, yytext());
            } 
            // fall through
          case 74: break;
          case 21: 
            { string.append(yytext());
            } 
            // fall through
          case 75: break;
          case 22: 
            { yybegin(YYINITIAL); return new Symbol(sym.STR, string.toString());
            } 
            // fall through
          case 76: break;
          case 23: 
            { return new Symbol(sym.IGUALDAD);
            } 
            // fall through
          case 77: break;
          case 24: 
            { return new Symbol(sym.NOIGUAL);
            } 
            // fall through
          case 78: break;
          case 25: 
            { return new Symbol(sym.MENORIGUAL);
            } 
            // fall through
          case 79: break;
          case 26: 
            { return new Symbol(sym.MAYORIGUAL);
            } 
            // fall through
          case 80: break;
          case 27: 
            { return new Symbol(sym.AND);
            } 
            // fall through
          case 81: break;
          case 28: 
            { return new Symbol(sym.OR);
            } 
            // fall through
          case 82: break;
          case 29: 
            { return new Symbol(sym.IF);
            } 
            // fall through
          case 83: break;
          case 30: 
            { return new Symbol(sym.DO);
            } 
            // fall through
          case 84: break;
          case 31: 
            { string.append('\"');
            } 
            // fall through
          case 85: break;
          case 32: 
            { string.append('\r');
            } 
            // fall through
          case 86: break;
          case 33: 
            { string.append('\n');
            } 
            // fall through
          case 87: break;
          case 34: 
            { string.append('\t');
            } 
            // fall through
          case 88: break;
          case 35: 
            { yybegin(UNICODE);
            } 
            // fall through
          case 89: break;
          case 36: 
            { string.append('\\');
            } 
            // fall through
          case 90: break;
          case 37: 
            { return new Symbol(sym.IMPLICA);
            } 
            // fall through
          case 91: break;
          case 38: 
            { return new Symbol(sym.INT);
            } 
            // fall through
          case 92: break;
          case 39: 
            { return new Symbol(sym.FOR);
            } 
            // fall through
          case 93: break;
          case 40: 
            { return new Symbol(sym.REAL, yytext());
            } 
            // fall through
          case 94: break;
          case 41: 
            { return new Symbol(sym.CARACTER,String.valueOf((int)yytext().charAt(yytext().length()-2)));
            } 
            // fall through
          case 95: break;
          case 42: 
            { return new Symbol(sym.ELSE);
            } 
            // fall through
          case 96: break;
          case 43: 
            { return new Symbol(sym.TRUE);
            } 
            // fall through
          case 97: break;
          case 44: 
            { return new Symbol(sym.CHAR);
            } 
            // fall through
          case 98: break;
          case 45: 
            { int code = Integer.parseInt(yytext(),16); string.append((char)code); yybegin(STRING);
            } 
            // fall through
          case 99: break;
          case 46: 
            { return new Symbol(sym.FLOAT);
            } 
            // fall through
          case 100: break;
          case 47: 
            { return new Symbol(sym.FALSE);
            } 
            // fall through
          case 101: break;
          case 48: 
            { return new Symbol(sym.WHILE);
            } 
            // fall through
          case 102: break;
          case 49: 
            { return new Symbol(sym.PRINT);
            } 
            // fall through
          case 103: break;
          case 50: 
            { return new Symbol(sym.CARACTER, String.valueOf(Integer.parseInt(yytext().substring(3,yytext().length()-1),16)));
            } 
            // fall through
          case 104: break;
          case 51: 
            { return new Symbol(sym.FORALL);
            } 
            // fall through
          case 105: break;
          case 52: 
            { return new Symbol(sym.STRING);
            } 
            // fall through
          case 106: break;
          case 53: 
            { return new Symbol(sym.BOOLEAN);
            } 
            // fall through
          case 107: break;
          case 54: 
            { return new Symbol(sym.LEN);
            } 
            // fall through
          case 108: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
